version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "powderbot2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18tfme8507set"
s3_prefix = "powderbot2"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
